Script started on 2016年03月14日 (週一) 21時34分13秒
]0;F74046145@2015cpp: ~/lab1F74046145@2015cpp:~/lab1$ whoamil [K[K; pwd
F74046145
/home/F74046145/lab1
]0;F74046145@2015cpp: ~/lab1F74046145@2015cpp:~/lab1$ git comfig[K[K[K[Knfig -l
user.name=michaelliao0826
user.email=a194748a@gmail.com
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.lab1.url=git@github.com:michaelliao0826/lab1.git
remote.lab1.fetch=+refs/heads/*:refs/remotes/lab1/*
]0;F74046145@2015cpp: ~/lab1F74046145@2015cpp:~/lab1$ git clone heep[K[K[Kttps://github.com/michaelliao0826/lab1.git
fatal: destination path 'lab1' already exists and is not an empty directory.
]0;F74046145@2015cpp: ~/lab1F74046145@2015cpp:~/lab1$ exit

Script done on 2016年03月14日 (週一) 21時35分25秒
